/**
 * Writes supabase/migrations/20260929120100_world_seed.sql from lib/store/seed.ts, so the shared world starts
 * with exactly the same community content as the on-device preview.
 *
 *   node --experimental-strip-types tools/gen-world-seed.mts
 */
import { writeFileSync } from 'node:fs'
import { seedWorld } from '../lib/store/seed.ts'

const w = seedWorld(0) // timestamps become offsets from the moment the migration runs

const q = (v: unknown): string => {
  if (v === null || v === undefined) return 'null'
  if (typeof v === 'number') return String(v)
  if (typeof v === 'boolean') return v ? 'true' : 'false'
  if (Array.isArray(v)) return v.length ? `array[${v.map(q).join(', ')}]::text[]` : `'{}'::text[]`
  return `'${String(v).replace(/'/g, "''")}'`
}
const at = (offset: number) => `now() + interval '${Math.round(offset)} milliseconds'`
const json = (v: unknown) => (v === undefined ? 'null' : `${q(JSON.stringify(v))}::jsonb`)

const rows = (table: string, cols: string[], values: string[][]) =>
  `insert into public.${table} (${cols.join(', ')}) values\n${values.map((v) => `  (${v.join(', ')})`).join(',\n')}\non conflict do nothing;\n`

const out: string[] = [
  '-- Generated by tools/gen-world-seed.mts from lib/store/seed.ts — do not edit by hand.',
  '-- PLACES community content: the guide, founding creators and their posts, courses, shops and opportunities.',
  '',
  rows(
    'profiles',
    ['id', 'username', 'name', 'avatar', 'bio', 'location', 'headline', 'interests', 'skills', 'base_followers', 'base_following', 'joined_at'],
    w.people.map((p) => [q(p.id), q(p.username), q(p.name), q(p.avatar), q(p.bio), q(p.location), q(p.headline), q(p.interests), q(p.skills), q(p.baseFollowers ?? 0), q(p.baseFollowing ?? 0), at(p.joinedAt)]),
  ),
  rows(
    'posts',
    ['id', 'author_id', 'body', 'image', 'link', 'location', 'poll', 'audience', 'created_at', 'base_likes', 'base_comments'],
    w.posts.map((p) => [q(p.id), q(p.authorId), q(p.body), q(p.image), q(p.link), q(p.location), json(p.poll?.map(({ id, label }) => ({ id, label }))), q(p.audience), at(p.createdAt), q(p.baseLikes ?? 0), q(p.baseComments ?? 0)]),
  ),
  rows(
    'post_comments',
    ['id', 'post_id', 'author_id', 'body', 'created_at'],
    w.posts.flatMap((p) => p.comments.map((c) => [q(c.id), q(p.id), q(c.authorId), q(c.body), at(c.createdAt)])),
  ),
  rows(
    'courses',
    ['id', 'expert_id', 'title', 'subtitle', 'description', 'image', 'kind', 'topic', 'base_members', 'starts_at', 'price'],
    w.courses.map((c) => [q(c.id), q(c.expertId), q(c.title), q(c.subtitle), q(c.description), q(c.image), q(c.kind), q(c.topic), q(c.baseMembers), c.startsAt === undefined ? 'null' : at(c.startsAt), q(c.price ?? null)]),
  ),
  rows(
    'course_lessons',
    ['id', 'course_id', 'position', 'title', 'minutes'],
    w.courses.flatMap((c) => c.lessons.map((l, i) => [q(l.id), q(c.id), q(i), q(l.title), q(l.minutes)])),
  ),
  rows(
    'lesson_bodies',
    ['lesson_id', 'course_id', 'body'],
    w.courses.flatMap((c) => c.lessons.map((l) => [q(l.id), q(c.id), q(l.body)])),
  ),
  rows(
    'discussions',
    ['id', 'author_id', 'title', 'body', 'category', 'tone', 'created_at', 'base_upvotes', 'base_replies'],
    w.discussions.map((d) => [q(d.id), q(d.authorId), q(d.title), q(d.body), q(d.category), q(d.tone), at(d.createdAt), q(d.baseUpvotes ?? 0), q(d.baseReplies ?? 0)]),
  ),
  rows(
    'discussion_replies',
    ['id', 'discussion_id', 'author_id', 'body', 'created_at'],
    w.discussions.flatMap((d) => d.replies.map((r) => [q(r.id), q(d.id), q(r.authorId), q(r.body), at(r.createdAt)])),
  ),
  rows(
    'shops',
    ['id', 'owner_id', 'name', 'category', 'description', 'image', 'created_at'],
    w.shops.map((x) => [q(x.id), q(x.ownerId), q(x.name), q(x.category), q(x.description), q(x.image), at(x.createdAt)]),
  ),
  rows(
    'products',
    ['id', 'shop_id', 'title', 'description', 'price', 'image', 'category', 'ships', 'created_at'],
    w.products.map((p) => [q(p.id), q(p.shopId), q(p.title), q(p.description), q(p.price), q(p.image), q(p.category), q(!!p.ships), at(p.createdAt)]),
  ),
  rows(
    'opportunities',
    ['id', 'posted_by', 'title', 'org', 'icon', 'icon_tone', 'location', 'type', 'kind', 'tags', 'pay', 'description', 'created_at'],
    w.opportunities.map((o) => [q(o.id), q(o.postedById), q(o.title), q(o.org), q(o.icon), q(o.iconTone), q(o.location), q(o.type), q(o.kind), q(o.tags), q(o.pay), q(o.description), at(o.createdAt)]),
  ),
]

writeFileSync(new URL('../supabase/migrations/20260929120100_world_seed.sql', import.meta.url), out.join('\n'))
console.log('Wrote supabase/migrations/20260929120100_world_seed.sql')
