-- Generated by tools/gen-world-seed.mts from lib/store/seed.ts — do not edit by hand.
-- PLACES community content: the guide, founding creators and their posts, courses, shops and opportunities.

insert into public.profiles (id, username, name, avatar, bio, location, headline, interests, skills, base_followers, base_following, joined_at) values
  ('p_josie', 'josie', 'Josie', '/media/avatar-josie.webp', 'Creator, mom, entrepreneur. Building a more conscious and connected world. ✨', 'Florida, USA', 'Content creator & community builder', array['Sustainable living', 'Wellness', 'Handmade']::text[], array['Content creation', 'Brand design', 'Community building']::text[], 1200, 245, now() + interval '-17280000000 milliseconds'),
  ('p_maya', 'mayamakes', 'Maya Chen', '/media/avatar-a.webp', 'Ceramicist and plant person. Slow objects for slow mornings.', 'Portland, USA', 'Founder, Luna & Co.', array['Ceramics', 'Plants', 'Design']::text[], array['Ceramics', 'Product photography']::text[], 3400, 0, now() + interval '-17280000000 milliseconds'),
  ('p_leo', 'leohart', 'Leo Hart', '/media/avatar-b.webp', 'Teaching sustainable living one small habit at a time.', 'Lisbon, Portugal', 'Sustainability educator', array['Sustainability', 'Gardening', 'Cycling']::text[], array['Teaching', 'Permaculture']::text[], 8900, 0, now() + interval '-17280000000 milliseconds'),
  ('p_ana', 'anaroams', 'Ana Ruiz', '/media/avatar-c.webp', 'Remote team lead. Hiring kind, curious people.', 'Mexico City, Mexico', 'People & operations lead', array['Remote work', 'Travel', 'Hiring']::text[], array['Operations', 'Recruiting']::text[], 2100, 0, now() + interval '-17280000000 milliseconds'),
  ('p_guide', 'guide', 'PLACES Guide', '/media/avatar-guide.webp', 'Here to help you find your way around PLACES.', 'Everywhere', 'Your guide to PLACES', '{}'::text[], '{}'::text[], 0, 0, now() + interval '-17280000000 milliseconds')
on conflict do nothing;

insert into public.posts (id, author_id, body, image, link, location, poll, audience, created_at, base_likes, base_comments) values
  ('post_1', 'p_josie', 'A slower, brighter, more intentional internet is possible. 💚', '/media/post-landscape.webp', null, null, null, 'public', now() + interval '-7200000 milliseconds', 128, 23),
  ('post_2', 'p_maya', 'Opened my little ceramics shop in MarketPlace this morning. Thank you all for the encouragement!', '/media/prod-mug.webp', null, null, null, 'public', now() + interval '-18000000 milliseconds', 342, 51),
  ('post_3', 'p_leo', 'Which small habit made the biggest difference for you this year?', null, null, null, '[{"id":"o1","label":"Composting"},{"id":"o2","label":"Buying second-hand"},{"id":"o3","label":"Cycling to work"}]'::jsonb, 'public', now() + interval '-32400000 milliseconds', 97, 12),
  ('post_4', 'p_ana', 'We just opened three remote roles in WorkPlace. If you care about people and love a tidy spreadsheet, come say hi.', null, null, 'Mexico City', null, 'public', now() + interval '-103680000 milliseconds', 64, 9)
on conflict do nothing;

insert into public.post_comments (id, post_id, author_id, body, created_at) values
  ('c_1', 'post_1', 'p_leo', 'This is the internet I want to live in.', now() + interval '-3600000 milliseconds')
on conflict do nothing;

insert into public.courses (id, expert_id, title, subtitle, description, image, kind, topic, base_members, starts_at, price) values
  ('crs_sustainable', 'p_leo', 'Sustainable Living', 'A practical guide', 'Small, realistic changes for a lighter footprint at home — food, energy, stuff and community.', '/media/learn-sustainable.webp', 'guide', 'Sustainability', 120000, null, null),
  ('crs_digital', 'p_ana', 'Digital Skills', 'Build your future', 'The practical tools of modern remote work: writing clearly, organising your work and collaborating online.', '/media/learn-digital.webp', 'course', 'Careers', 68000, null, null),
  ('crs_wellness', 'p_josie', 'Health & Wellness', 'Mind • Body', 'Gentle routines for energy, focus and rest — built around real, busy lives.', '/media/learn-health.webp', 'course', 'Wellness', 74000, null, null),
  ('crs_writing', 'p_maya', 'Creative Writing', 'Live workshop', 'A friendly live workshop: short prompts, shared drafts and kind feedback.', '/media/learn-writing.webp', 'live', 'Creativity', 31000, now() + interval '172800000 milliseconds', null),
  ('crs_garden', 'p_leo', 'Grow Your Own', 'Balcony gardening', 'Herbs, salad and tomatoes in small spaces — containers, soil, light and watering.', '/media/learn-garden.webp', 'guide', 'Sustainability', 42000, null, null),
  ('crs_shop', 'p_maya', 'Start a Small Shop', 'From idea to first sale', 'Open your MarketPlace shop: products, photos, pricing and getting paid with Stripe.', '/media/learn-shop.webp', 'course', 'Business', 27000, null, 2900)
on conflict do nothing;

insert into public.course_lessons (id, course_id, position, title, minutes) values
  ('sus_l1', 'crs_sustainable', 0, 'Start with one habit', 6),
  ('sus_l2', 'crs_sustainable', 1, 'Food without waste', 9),
  ('sus_l3', 'crs_sustainable', 2, 'Energy at home', 8),
  ('sus_l4', 'crs_sustainable', 3, 'Buy less, buy better', 7),
  ('dig_l1', 'crs_digital', 0, 'Writing that gets read', 10),
  ('dig_l2', 'crs_digital', 1, 'Organising your week', 8),
  ('dig_l3', 'crs_digital', 2, 'Working async', 9),
  ('dig_l4', 'crs_digital', 3, 'Your portfolio', 12),
  ('wel_l1', 'crs_wellness', 0, 'A calmer morning', 6),
  ('wel_l2', 'crs_wellness', 1, 'Movement you enjoy', 7),
  ('wel_l3', 'crs_wellness', 2, 'Rest on purpose', 8),
  ('wri_l1', 'crs_writing', 0, 'Warm-up prompts', 15),
  ('wri_l2', 'crs_writing', 1, 'Finding your voice', 20),
  ('gar_l1', 'crs_garden', 0, 'Light and containers', 7),
  ('gar_l2', 'crs_garden', 1, 'Soil and feeding', 6),
  ('gar_l3', 'crs_garden', 2, 'What to grow first', 8),
  ('shp_l1', 'crs_shop', 0, 'Choose three products', 8),
  ('shp_l2', 'crs_shop', 1, 'Photos that sell', 10),
  ('shp_l3', 'crs_shop', 2, 'Pricing with confidence', 9),
  ('shp_l4', 'crs_shop', 3, 'Getting paid', 7)
on conflict do nothing;

insert into public.lesson_bodies (lesson_id, course_id, body) values
  ('sus_l1', 'crs_sustainable', 'Pick the change that is easiest for you, not the one that looks best. Consistency beats intensity: a habit you keep for a year does more than a dramatic week.'),
  ('sus_l2', 'crs_sustainable', 'Plan three meals ahead, shop with a list and keep a "use first" shelf in the fridge. Freeze bread and herbs before they turn. Compost what is left.'),
  ('sus_l3', 'crs_sustainable', 'Draught-proof doors and windows, lower the heating by one degree and wash at 30°C. Switch to a renewable tariff if one is available where you live.'),
  ('sus_l4', 'crs_sustainable', 'Borrow, repair and buy second-hand first. When you buy new, choose things that can be mended and will be loved for a long time.'),
  ('dig_l1', 'crs_digital', 'Lead with the point. Use short paragraphs and one idea per message. End with the decision or action you need.'),
  ('dig_l2', 'crs_digital', 'Keep one list. Sort by what moves your goals, not by what is loudest. Block focus time before meetings fill it.'),
  ('dig_l3', 'crs_digital', 'Share context in writing, record short videos for walkthroughs and agree on response times with your team.'),
  ('dig_l4', 'crs_digital', 'Show three pieces of work with the problem, what you did and the result. Keep it short and link to it everywhere.'),
  ('wel_l1', 'crs_wellness', 'Keep the first ten minutes screen-free. Water, light and a short walk set the tone for the day.'),
  ('wel_l2', 'crs_wellness', 'The best exercise is the one you will do. Two short walks count. So does dancing in the kitchen.'),
  ('wel_l3', 'crs_wellness', 'Protect a wind-down hour. Dim lights, write tomorrow’s list and put the phone in another room.'),
  ('wri_l1', 'crs_writing', 'Write for five minutes without stopping. Do not edit. Circle one sentence you like.'),
  ('wri_l2', 'crs_writing', 'Read your circled sentence aloud. What makes it sound like you? Write a paragraph that keeps that sound.'),
  ('gar_l1', 'crs_garden', 'Most edibles need six hours of sun. Use pots with drainage holes and at least 20 cm of depth.'),
  ('gar_l2', 'crs_garden', 'Use peat-free compost and feed every two weeks in summer.'),
  ('gar_l3', 'crs_garden', 'Start with mint, basil, lettuce and cherry tomatoes. They forgive mistakes.'),
  ('shp_l1', 'crs_shop', 'Start small. Three great products tell a clearer story than thirty.'),
  ('shp_l2', 'crs_shop', 'Use daylight, a plain background and show the object in use.'),
  ('shp_l3', 'crs_shop', 'Materials + time + overheads, then check what similar makers charge. Do not undercharge.'),
  ('shp_l4', 'crs_shop', 'Create a Stripe Payment Link for each product and paste it into your listing. Buyers pay you directly.')
on conflict do nothing;

insert into public.discussions (id, author_id, title, body, category, tone, created_at, base_upvotes, base_replies) values
  ('dsc_1', 'p_ana', 'Best remote jobs for beginners?', 'I am switching careers and would love to hear which remote roles are realistic to start in without years of experience.', 'WorkPlace', 'teal', now() + interval '-7200000 milliseconds', 1200, 341),
  ('dsc_2', 'p_maya', 'Tips for starting an online store', 'What do you wish you had known before opening your first shop?', 'MarketPlace', 'coral', now() + interval '-18000000 milliseconds', 864, 187),
  ('dsc_3', 'p_leo', 'Favorite countries for digital nomads', 'Planning a year of slow travel. Where did you feel most at home while working remotely?', 'Travel', 'sun', now() + interval '-86400000 milliseconds', 2100, 420),
  ('dsc_4', 'p_josie', 'How do you keep a daily learning habit?', 'I start strong every month and then drift. What keeps you going?', 'Growth', 'lavender', now() + interval '-172800000 milliseconds', 540, 96),
  ('dsc_5', 'p_leo', 'Balcony tomatoes: pots or grow bags?', 'First summer growing food. Which worked better for you?', 'Gardening', 'leaf', now() + interval '-259200000 milliseconds', 212, 38)
on conflict do nothing;

insert into public.discussion_replies (id, discussion_id, author_id, body, created_at) values
  ('r_1', 'dsc_1', 'p_josie', 'Virtual assistant and customer support roles taught me so much. Both are in WorkPlace right now!', now() + interval '-3600000 milliseconds')
on conflict do nothing;

insert into public.shops (id, owner_id, name, category, description, image, created_at) values
  ('shp_sunsoil', 'p_leo', 'Sun & Soil', 'Home & Garden', 'Plants, pots and slow-living goods for sunny corners.', '/media/shop-sunsoil.webp', now() + interval '-7776000000 milliseconds'),
  ('shp_luna', 'p_maya', 'Luna & Co.', 'Handmade Goods', 'Hand-thrown ceramics and macramé, made in small batches.', '/media/shop-luna.webp', now() + interval '-5184000000 milliseconds'),
  ('shp_bloom', 'p_josie', 'Digital Bloom', 'Templates & Tools', 'Printable art, planners and templates for creative people.', '/media/shop-bloom.webp', now() + interval '-3888000000 milliseconds')
on conflict do nothing;

insert into public.products (id, shop_id, title, description, price, image, category, ships, created_at) values
  ('prd_prints', 'shp_bloom', 'Botanical Prints', 'A set of six printable botanical illustrations. Instant download, print at home up to A3.', 2800, '/media/prod-prints.webp', 'Digital', false, now() + interval '-864000000 milliseconds'),
  ('prd_hanger', 'shp_luna', 'Macrame Plant Hanger', 'Hand-knotted cotton hanger for pots up to 18 cm. Each one is slightly different.', 3600, '/media/prod-hanger.webp', 'Handmade', false, now() + interval '-691200000 milliseconds'),
  ('prd_journal', 'shp_sunsoil', 'Wellness Journal', 'A 12-week guided journal for gentle routines, gratitude and rest.', 2200, '/media/prod-journal.webp', 'Wellness', false, now() + interval '-518400000 milliseconds'),
  ('prd_mug', 'shp_luna', 'Ceramic Mug Set', 'Two hand-thrown stoneware mugs in soft cream and blush glazes. Dishwasher safe.', 4800, '/media/prod-mug.webp', 'Handmade', false, now() + interval '-345600000 milliseconds'),
  ('prd_planter', 'shp_sunsoil', 'Terracotta Planter Trio', 'Three unglazed terracotta planters with saucers — small, medium and large.', 3400, '/media/shop-sunsoil.webp', 'Home', false, now() + interval '-259200000 milliseconds'),
  ('prd_planner', 'shp_bloom', 'Creator Planner Template', 'Notion + printable planner for content calendars, launches and weekly reviews.', 1500, '/media/shop-bloom.webp', 'Digital', false, now() + interval '-172800000 milliseconds'),
  ('prd_session', 'shp_bloom', 'Brand Photo Session (1h)', 'A one-hour remote session to plan and art-direct your product photos.', 9000, '/media/shop-luna.webp', 'Services', false, now() + interval '-86400000 milliseconds')
on conflict do nothing;

insert into public.opportunities (id, posted_by, title, org, icon, icon_tone, location, type, kind, tags, pay, description, created_at) values
  ('opp_1', 'p_leo', 'Social Media Content Creator', 'Sun & Soil', 'leaf', 'leaf', 'Remote', 'Part Time', 'job', array['Marketing', 'Creative']::text[], '$25–35/hr', 'Plan and create short videos and posts that show slow living at its best. 15–20 hours a week, flexible schedule.', now() + interval '-10800000 milliseconds'),
  ('opp_2', 'p_ana', 'Virtual Assistant', 'Remote Creators Co.', 'sun', 'sun', 'Remote', 'Flexible', 'job', array['Admin', 'Operations']::text[], '$18–25/hr', 'Inbox, calendar and light bookkeeping for a small creative team. Great first remote role.', now() + interval '-28800000 milliseconds'),
  ('opp_3', 'p_maya', 'Website Designer', 'Luna & Co.', 'waves', 'sky', 'Remote', 'Project', 'project', array['Web Design', 'Creative']::text[], '$500–1,500', 'Refresh a small ceramics shop website: homepage, product pages and a simple story page.', now() + interval '-86400000 milliseconds'),
  ('opp_4', 'p_ana', 'Customer Support (Remote)', 'Remote Creators Co.', 'gem', 'teal', 'Remote', 'Full Time', 'job', array['Support', 'Customer Service']::text[], '$45–60k', 'Help our members with kindness and clarity across chat and email. Training provided.', now() + interval '-129600000 milliseconds'),
  ('opp_5', 'p_guide', 'Community Manager', 'PLACES', 'megaphone', 'coral', 'Lisbon · Hybrid', 'Full Time', 'team', array['Community', 'Events']::text[], '$52–64k', 'Grow warm, well-moderated communities in MindPlace and host monthly live events.', now() + interval '-172800000 milliseconds'),
  ('opp_6', 'p_josie', 'Brand Illustrator', 'Digital Bloom', 'palette', 'lavender', 'Remote', 'Freelance', 'service', array['Illustration', 'Branding']::text[], '$60–90/hr', 'Hand-drawn botanical illustrations for a new print collection. Portfolio required.', now() + interval '-259200000 milliseconds')
on conflict do nothing;
